{% set name = "qubekit" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qubekit/QUBEKit/archive/{{ version }}.tar.gz
  sha256: ace229c5ad724bcbab566d3a858c4712543d77dfbea86412dd5a9e6b8ce72f91


build:
  entry_points:
    - QUBEKit = qubekit.cli.cli:cli
    - qubekit = qubekit.cli.cli:cli
    - QUBEKit-pro = qubekit.proteins.protein_run:main
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.18.1
    - scipy
    - rdkit
    - torsiondrive
    - ambertools
    - networkx >=2.4
    - matplotlib-base
    - qcengine >=0.18.0
    - jinja2
    - typing-extensions
    - click
    - tqdm
    - openff-toolkit-base >=0.10.0
    - forcebalance
    - xtb-python


test:
  imports:
    - qubekit
  requires:
    - rdkit
    - python {{ python_min }}
  commands:
    - qubekit --help

about:
  home: https://github.com/qubekit/QUBEKit
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Quantum mechanical bespoke force field derivation toolkit
  doc_url: https://github.com/qubekit/QUBEKit
  description: QUBEKit is a Python based force field parameter derivation toolkit. Our aims are to allow users to quickly derive molecular mechanics parameters directly from quantum mechanical calculations.
  dev_url: https://github.com/qubekit/QUBEKit

extra:
  recipe-maintainers:
    - jthorton
    - CRingrose94
